export const apiPaths = {
  login: '/auth/login',
  register: '/auth/register',
  forgotPassword: '/auth/forgot-password',
  resetPassword: '/auth/reset-password',
  usersProfile: '/users/profile',
  categories: '/categories',
  categoriesFlat: '/categories/flat',
  category: (id: string) => `/categories/${id}`,
  products: '/products',
  productsByStore: (storeId: string) => `/products/store/${storeId}`,
  product: (id: string) => `/products/${id}`,
  cart: '/cart',
  cartSummary: '/cart/summary',
  cartItems: '/cart/items',
  cartItem: (itemId: string) => `/cart/items/${itemId}`,
  favorites: '/favorites',
  favoriteCheck: (productId: string) => `/favorites/${productId}/check`,
  favoriteByProduct: (productId: string) => `/favorites/${productId}`,
  stores: '/stores',
  storeLookup: (term: string) => `/stores/lookup/${encodeURIComponent(term)}`,
  storesMy: '/stores/my/store',
  store: (id: string) => `/stores/${id}`,
  adminDashboard: '/admin/dashboard',
  adminUsers: '/admin/users',
  adminUser: (id: string) => `/admin/users/${id}`,
  adminUserToggleActive: (id: string) => `/admin/users/${id}/toggle-active`,
  adminStores: '/admin/stores',
  adminStore: (id: string) => `/admin/stores/${id}`,
  adminStoreCommission: (id: string) => `/admin/stores/${id}/commission`,
  adminProducts: '/admin/products',
  adminOrders: '/admin/orders',
  adminReportsSales: '/admin/reports/sales',
  sellerDashboard: '/seller/dashboard',
  sellerProducts: '/seller/products',
  sellerStore: (id: string) => `/seller/stores/${id}`,
  sellerReportsSales: '/seller/reports/sales',
  storesRejected: '/stores/rejected',
  storeApprove: (id: string) => `/stores/${id}/approve`,
  storeReject: (id: string) => `/stores/${id}/reject`,
  orders: '/orders',
  ordersMy: '/orders/my',
  order: (id: string) => `/orders/${id}`,
  ordersStore: '/orders/store',
  ordersStoreReport: '/orders/store/report',
  orderStatus: (id: string) => `/orders/${id}/status`,
  paymentByOrder: (orderId: string) => `/payments/order/${orderId}`,
  filesUpload: '/files/upload',
  filesUploadMultiple: '/files/upload/multiple',
  filesDownload: '/files/download',
  filesMetadata: '/files/metadata',
  filesDelete: '/files',
} as const;
