export const apiPaths = {
  login: '/auth/login',
  register: '/auth/register',
  categories: '/categories',
  categoriesFlat: '/categories/flat',
  category: (id: string) => `/categories/${id}`,
  products: '/products',
  product: (id: string) => `/products/${id}`,
  cart: '/cart',
  cartSummary: '/cart/summary',
  cartItems: '/cart/items',
  cartItem: (itemId: string) => `/cart/items/${itemId}`,
  favorites: '/favorites',
  favoriteCheck: (productId: string) => `/favorites/${productId}/check`,
  favoriteByProduct: (productId: string) => `/favorites/${productId}`,
  adminDashboard: '/admin/dashboard',
  adminUsers: '/admin/users',
  adminUserToggleActive: (id: string) => `/admin/users/${id}/toggle-active`,
  adminStores: '/admin/stores',
  adminStoreCommission: (id: string) => `/admin/stores/${id}/commission`,
  adminProducts: '/admin/products',
  adminOrders: '/admin/orders',
  adminReportsSales: '/admin/reports/sales',
  storesRejected: '/stores/rejected',
  storeApprove: (id: string) => `/stores/${id}/approve`,
  storeReject: (id: string) => `/stores/${id}/reject`,
  ordersStore: '/orders/store',
  ordersStoreReport: '/orders/store/report',
  orderStatus: (id: string) => `/orders/${id}/status`,
} as const;
