export const routePaths = {
  catalog: '/',
  /** Catálogo sin redirección de admin (para revisar la tienda) */
  browse: '/browse',
  product: '/product',
  productDetail: (id: string) => `/product/${id}`,
  login: '/auth/login',
  register: '/auth/register',
  forgotPassword: '/auth/forgot-password',
  resetPassword: '/auth/reset-password',
  favorites: '/favorites',
  stores: '/stores',
  storeDetail: (id: string) => `/stores/${id}`,
  cart: '/cart',
  orders: '/orders',
  orderDetail: (id: string) => `/orders/${id}`,
  settings: '/settings',
  seller: '/seller',
  sellerStoreProducts: (storeId: string) => `/seller/stores/${storeId}/products`,
  sellerProductNew: '/seller/products/new',
  sellerProductEdit: (id: string) => `/seller/products/${id}/edit`,
  sellerOrders: '/seller/orders',
  sellerReport: '/seller/report',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminStores: '/admin/stores',
  adminModeration: '/admin/moderation',
  adminProducts: '/admin/products',
  adminOrders: '/admin/orders',
  adminCategories: '/admin/categories',
} as const;
