export const routePaths = {
  catalog: '/',
  /** Catálogo sin redirección de admin (para revisar la tienda) */
  browse: '/browse',
  product: '/product',
  productDetail: (id: string) => `/product/${id}`,
  login: '/auth/login',
  register: '/auth/register',
  favorites: '/favorites',
  cart: '/cart',
  settings: '/settings',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminStores: '/admin/stores',
  adminModeration: '/admin/moderation',
  adminProducts: '/admin/products',
  adminOrders: '/admin/orders',
  adminSales: '/admin/sales',
  adminCategories: '/admin/categories',
} as const;
