export const queryKeys = {
  categories: ['categories'] as const,
  categoriesFlat: ['categories', 'flat'] as const,
  products: (filters?: Record<string, unknown>) => ['products', filters ?? {}] as const,
  product: (id: string) => ['product', id] as const,
  cart: ['cart'] as const,
  favorites: ['favorites'] as const,
  favoriteCheck: (productId: string) => ['favorites', 'check', productId] as const,
  adminDashboard: ['admin', 'dashboard'] as const,
  adminUsers: ['admin', 'users'] as const,
  adminStores: ['admin', 'stores'] as const,
  adminProducts: ['admin', 'products'] as const,
  adminOrders: ['admin', 'orders'] as const,
  adminSalesReport: ['admin', 'reports', 'sales'] as const,
  adminPlatformReport: ['admin', 'orders', 'store-report'] as const,
  storesRejected: ['stores', 'rejected'] as const,
};
