export const queryKeys = {
  categories: ['categories'] as const,
  categoriesFlat: ['categories', 'flat'] as const,
  products: (filters?: Record<string, unknown>) => ['products', filters ?? {}] as const,
  productsByStore: (storeId: string, filters?: Record<string, unknown>) =>
    ['products', 'store', storeId, filters ?? {}] as const,
  product: (id: string) => ['product', id] as const,
  cart: ['cart'] as const,
  cartSummary: ['cart', 'summary'] as const,
  favorites: ['favorites'] as const,
  favoriteCheck: (productId: string) => ['favorites', 'check', productId] as const,
  userProfile: ['users', 'profile'] as const,
  publicStores: ['stores', 'public'] as const,
  storePublicLookup: (term: string) => ['stores', 'public', 'lookup', term] as const,
  myStores: ['stores', 'my'] as const,
  ordersMy: ['orders', 'my'] as const,
  order: (id: string) => ['orders', id] as const,
  ordersStore: ['orders', 'store'] as const,
  paymentByOrder: (orderId: string) => ['payments', 'order', orderId] as const,
  adminDashboard: ['admin', 'dashboard'] as const,
  adminUsers: ['admin', 'users'] as const,
  adminStores: ['admin', 'stores'] as const,
  adminStore: (id: string) => ['admin', 'stores', id] as const,
  adminProducts: ['admin', 'products'] as const,
  adminOrders: ['admin', 'orders'] as const,
  adminSalesReport: ['admin', 'reports', 'sales'] as const,
  adminPlatformReport: ['admin', 'orders', 'store-report'] as const,
  storesRejected: ['stores', 'rejected'] as const,
  sellerDashboard: ['seller', 'dashboard'] as const,
  sellerProducts: ['seller', 'products'] as const,
  sellerStore: (id: string) => ['seller', 'stores', id] as const,
  sellerSalesReport: ['seller', 'reports', 'sales'] as const,
  sellerStoreReport: ['seller', 'orders', 'store-report'] as const,
};
